### PR TITLE
translations and typo

### PR DESCRIPTION
**Pull request by vltr**
well, I fixed / updated some translations to pt_br (using .pot file from source) and a minor typo fix in gschema (summary tag, nothing significant), like I [promised](https://github.com/dmo60/CoverflowAltTab/pull/48#issuecomment-219420701) on PR #48 :smiley:

### CODE REVIEW

**Comment by p91paul** [comment]
I am sorry, I did not update the .pot file with the new strings, working on the individual .po files instead. I'll try and do that ASAP!

**Comment by vltr** [comment]
@p91paul oh, no problem! I thought the .pot file in the root path was the template :smile:

As soon as you update it, just leave a beep here so I can update the portuguese side of it :wink:

**Comment by p91paul** [comment]
Done, the .pot in the master branch is now up-to-date. Thanks!

**Comment by vltr** [comment]
Great! I'll update my repo and increment the PR :)

**Comment by vltr** [comment]
Done! :smiley:

**Comment by p91paul** [comment]
Merged, thanks!

**Comment by vltr** [comment]
Uhul :+1:

**Pull request merged**
