### PR TITLE
Per-monitor task switching

### PR DESCRIPTION
**Pull request by pospeselr**
Added setting to only switch between windows on the current 'active' monitor (monitor where the mouse cursor is).  

Also disabled the _enableMonitorFix method in switcher.js.  I'm not sure what this is trying to accomplish but it results in very odd behaviour with my multi-mon setup (rectangles at bottom of some of my monitors not being rendered with the task-switch animations).  What problem is this function trying to fix?

thanks,
-Richard

### CODE REVIEW

**Comment by dsebastien** [comment]
Would love to get this!

**Comment by p91paul** [comment]
Will try to merge in a branch and update to current code.

**Comment by pospeselr** [comment]
lol amazing

**Comment by p91paul** [comment]
Yes, this did get mainlined after 5 years :D

**Pull request merged**
