### PR TITLE
Allow easing of windows back to their pre-switcher positions.

### PR DESCRIPTION
**Pull request by dsheeler**
Make selected window on top of the rest.  First crack at solving #155.

### CODE REVIEW

**Review by machitgarha — APPROVED** [review]
Great job! Thanks, @dsheeler!

I think with this PR, we are closer to fix #108 as well.

P.S.: The awful point is, I cannot test these changes, or even play with this. I'm on Wayland, so I cannot restart Gnome session. The reason is not Wayland itself, however, Gnome extension-manager (i.e. `Main.extensionManager`) cannot reload an extension properly, when playing with it in Looking Glass. And it's really sad.

**Comment by dsheeler** [comment]
@machitgarha, thank you!  I think you're right about #108, too.  

I really dislike that gnome-shell under wayland can't restart like it can under X11.  I used wayland for a bit but came back to X11 for better screen sharing for zoom, and it has the added benefit of easier hacking on extensions. Is there a way to reload an extension through looking glass?  I did not know that!  I always restart the shell.

**Comment by machitgarha** [comment]
@dsheeler

About the looking class, you can use `Main.extensionManager` methods for that, including `loadExtension()`, `unloadExtension()`, `enableExtension()`, and so on. They all get an extension instance created by `createExtensionObject()` as their input.

Loading an extension for the first times works pretty well. But, there's a caching issue preventing the extension reloading feature from working properly. If you are interested, you can read the discussion [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2513). I think it's not Wayland's fault.

**Comment by p91paul** [comment]
Not merging this because of the draft state. I did not test it, let me know when you think it's ready!

**Comment by dsheeler** [comment]
@p91paul, @machitgarha, etc.  I see a problem: the previews of minimized windows ease to the 0,0 position instead of where the window was.  Do you guys know why that might be?

**Comment by p91paul** [comment]
@dsheeler I don't see a problem with that. Minimized windows don't really have a position until they are de-minimized again. If it's just the animation that goes to the top-left corner I'd let it be.

**Comment by dsheeler** [comment]
@p91paul, the problem is that when the switcher is destroyed, the preview is at (0, 0), but the window it represents pops into existence at the (x, y) it had before being minimized, so there's a glitch: 

https://user-images.githubusercontent.com/1632985/133263345-3c804939-f3c3-4dcc-8ad4-489127350028.mp4

To fix this, somehow we'd need to know the window position before it's minimized... is that available somewhere?  I tried simply getting the compositor for the window and easing to the compositors x and y, but that doesn't work.  I even print out the values and they seem valid.  I'm confused.

This code in switcher, in the _onDestroy() function is where this all happens:

       if (this._initialDelayTimeoutId === 0) {
            // preview windows
            let currentWorkspace = this._manager.workspace_manager.get_active_workspace();
            for (let [i, preview] of this._previews.entries()) {
                let metaWin = this._windows[i],
                    compositor = metaWin.get_compositor_private();

                // Move all non-activated windows behind the activated one
                if (i !== this._currentIndex) {
                    preview.make_bottom_layer(this.previewActor);
                }
                if (metaWin.minimized) {
                    print(compositor.x, compositor.y)  // these values seem good
                }
                this._manager.platform.tween(preview, {
                    opacity: (!metaWin.minimized && metaWin.get_workspace() == currentWorkspace
                        || metaWin.is_on_all_workspaces()) ? 255 : 0,

                    x: compositor.x - monitor.x,  // this ends up as (0, 0)
                    y: compositor.y - monitor.y,
                    width: compositor.width,
                    height: compositor.height,

                    translation_x: 0,
                    //rotation_angle_z: 360,
                    scale_x: 1,
                    scale_y: 1,
                    rotation_angle_y: 0.0,
                    onComplete: Lang.bind(this, this._onPreviewDestroyComplete),
                    time: this._settings.animation_time,
                    transition: TRANSITION_TYPE,
                });
            }

        }

**Comment by dsheeler** [comment]
@p91paul, I think this should be merged... The problem above can be worked on seperately

**Comment by p91paul** [comment]
Thank you!

**Pull request merged**
