### PR TITLE
Fix call to popModal.

### PR DESCRIPTION
**Pull request by dsheeler**
gnome 42 support #164

### CODE REVIEW

**Comment by p91paul** [comment]
did you test this with gnome 40 and 41? otherwise please drop older versions in metadata.json. Thanks!

**Comment by dsheeler** [comment]
I did not test on 40/41.  I'll drop them

**Comment by Neo-29** [comment]
can confirmit worked on 41...i even bypassed the version first without issues
it's 42 related

**Comment by dsheeler** [comment]
@Neo-29, It worked in 40 and 41 before my fix for 42, but I haven't tested if the fix for 42 breaks 40 or 41.

**Comment by Neo-29** [comment]
I guess your fix is not yet pushed on gnome extension?
Should I build it from source?

I know there's a package on AUR too.. Don't know if it follows the git update.

**Comment by dsheeler** [comment]
It's still not in the main branch, but if you have github command line client, if you clone the repository and run

`$ gh pr checkout 166`

you can get the code

**Pull request merged**
