### PR TITLE
add support for gnome 40

### PR DESCRIPTION
**Pull request by hiaselhans**
this adds support for gnome 40. Old shell versions are removed for simplicity and could be supported in branches?

The settings menu seems fully operational now and all works fine.

### CODE REVIEW

**Comment by hiaselhans** [comment]
fixes #143

**Comment by p91paul** [comment]
Thank you very much. I'll merge it so that others can test it easily.

**Comment by p91paul** [comment]
Just want you to know you helped me fix not one, but 4 extensions with this pull request.
Thanks.

**Comment by hiaselhans** [comment]
Very welcome @p91paul 

And thank you for maintaining all those extensions!

**Comment by molitona** [comment]
Doesn't exist till now despite a user commented that in extension page ?
------

> 
> 
> Now works on Arch Linux Gnome 40.0
> 
> Glad for the fast updates, I wasn't expecting the new version of Gnome, and this is one great extension. (Now just waiting for Dash to Dock!)

**Comment by p91paul** [comment]
> ## Doesn't exist till now despite a user commented that in extension page ?
> 
> > Now works on Arch Linux Gnome 40.0
> > Glad for the fast updates, I wasn't expecting the new version of Gnome, and this is one great extension. (Now just waiting for Dash to Dock!)

That user probably installed manually from github. Gnome 40 update was uploaded to extensions.gnome.org and is pending review, I expect it will be approved in a few days.

**Pull request merged**
