### PR TITLE
Structure cleanup

### LINKED ISSUE #186: Cleaning repository files up
The repository has duplicate/extra files, which should be removed. I wanted to clean stuff up, but am creating an issue before to make sure it will be accepted in the case of a PR.

The changes would be merging `CoverflowAltTab@*` directories contests into the root directory (and merging `metadata.json`) and removing those directories, and updating `buildforupload.sh` and `Makefile` files where they reference the directories.

### PR DESCRIPTION
**Pull request by machitgarha**
Closes #186.

The only thing that is removed during the process is the `LOCALINSTALL` feature. Many extensions do not support this way of installation, plus it's uncommon between users to install the extension into `/usr/local`. By the way, if you think it's necessary, it's relatively easy to bring it back.

BTW, I don't get the point of `*install_schema_systemwide` make jobs.

The new build process is done by `make build`, which creates a zip file in the `build/` directory.

Many of the binary files have been removed, including unused images, `gschema.compiled` and `.mo` files. The compiled binaries should only be made at the build stage, and shouldn't be tracked in the repository itself.

Also, updated po files, improved `Makefile`, and other small changes.

### CODE REVIEW

**Comment by p91paul** [comment]
I see you deleted the buildforupload.sh. The zip command there excluded some files from the archive (e.g. the .po files). Please make sure the new make build command provides the same exclusions and includes the same files (gschema.compiled, *.mo files), because those exclusions were required for acceptance on extensions.gnome.org.

**Comment by machitgarha** [comment]
@p91paul, I tested it already, `make build` uses `gnome-extensions pack` command which does the job, meaning it will build all `.mo` files while `.po` files not being included, making `gschemas.compiled` binary, etc. You can see the changes made to `Makefile` and test it yourself.

**Comment by p91paul** [comment]
Thank you for your clarification. I reviewed the pr from my phone and did not know what the pack command did :muscle:

**Comment by dsheeler** [comment]
@p91paul any objection to merging? If not, I will!

**Comment by p91paul** [comment]
no objection whatsoever, thanks to the both of you for the good work on this project.

**Pull request merged**
